"""Create small demonstration-only datasets for the public repo.

The files generated by this script mimic the schema and rough value ranges used
by the project, but they do not reproduce the original DataFest data or findings.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.campus_opportunity_score import compute_campus_opportunity_score
from src.config import DEMO_YEARS, SAMPLE_DATA_DIR, ensure_project_dirs

RNG = np.random.default_rng(2026)

COUNTY_METADATA = [
    {"county_fips": "20177", "county_name": "Shawnee", "distance_to_topeka_miles": 8, "distance_to_junction_city_miles": 67},
    {"county_fips": "20061", "county_name": "Geary", "distance_to_topeka_miles": 66, "distance_to_junction_city_miles": 6},
    {"county_fips": "20041", "county_name": "Dickinson", "distance_to_topeka_miles": 83, "distance_to_junction_city_miles": 31},
    {"county_fips": "20027", "county_name": "Clay", "distance_to_topeka_miles": 94, "distance_to_junction_city_miles": 40},
    {"county_fips": "20161", "county_name": "Riley", "distance_to_topeka_miles": 61, "distance_to_junction_city_miles": 19},
    {"county_fips": "20087", "county_name": "Jefferson", "distance_to_topeka_miles": 31, "distance_to_junction_city_miles": 88},
    {"county_fips": "20139", "county_name": "Osage", "distance_to_topeka_miles": 29, "distance_to_junction_city_miles": 86},
    {"county_fips": "20197", "county_name": "Wabaunsee", "distance_to_topeka_miles": 36, "distance_to_junction_city_miles": 46},
]


def _choose_campus(distance_to_topeka: float, distance_to_junction_city: float) -> str:
    if distance_to_topeka <= distance_to_junction_city:
        return RNG.choice(["Topeka", "Topeka", "Junction City"])
    return RNG.choice(["Junction City", "Junction City", "Topeka"])


def build_synthetic_encounters(n_rows: int = 360) -> pd.DataFrame:
    counties = pd.DataFrame(COUNTY_METADATA)
    weights = np.array([0.24, 0.17, 0.10, 0.08, 0.14, 0.09, 0.09, 0.09])
    chosen = counties.sample(n=n_rows, replace=True, weights=weights, random_state=2026).reset_index(drop=True)

    patient_ids = [f"PT{value:04d}" for value in RNG.integers(1, 170, size=n_rows)]
    encounter_ids = [f"ENC{value:05d}" for value in range(1, n_rows + 1)]
    encounter_dates = pd.to_datetime(
        RNG.choice(pd.date_range("2023-01-01", "2025-12-31", freq="D"), size=n_rows)
    )

    is_diabetes = RNG.choice([0, 1], size=n_rows, p=[0.20, 0.80])
    is_ed = RNG.choice([0, 1], size=n_rows, p=[0.78, 0.22])
    is_hospital_admittance = RNG.choice([0, 1], size=n_rows, p=[0.89, 0.11])
    is_observation = RNG.choice([0, 1], size=n_rows, p=[0.86, 0.14])

    campus = [
        _choose_campus(row.distance_to_topeka_miles, row.distance_to_junction_city_miles)
        for row in chosen.itertuples(index=False)
    ]
    distance_to_nearest = np.minimum(
        chosen["distance_to_topeka_miles"],
        chosen["distance_to_junction_city_miles"],
    ) + RNG.normal(0, 3, size=n_rows)

    encounters = pd.DataFrame(
        {
            "patient_id": patient_ids,
            "encounter_id": encounter_ids,
            "county_fips": chosen["county_fips"],
            "county_name": chosen["county_name"],
            "campus": campus,
            "encounter_date": encounter_dates.strftime("%Y-%m-%d"),
            "is_diabetes": is_diabetes,
            "is_ed": is_ed,
            "is_hospital_admittance": is_hospital_admittance,
            "is_observation": is_observation,
            "distance_to_nearest_campus_miles": np.round(np.clip(distance_to_nearest, 3, None), 1),
        }
    )
    return encounters


def build_synthetic_county_panel() -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for county in COUNTY_METADATA:
        base_patients = int(RNG.integers(120, 360))
        base_uninsurance = RNG.uniform(8.0, 14.0)
        for year in DEMO_YEARS:
            diabetes_patients = base_patients + int(RNG.integers(-25, 26)) + (year - DEMO_YEARS[0]) * int(RNG.integers(3, 11))
            acute_care_events = int(diabetes_patients * RNG.uniform(0.18, 0.38))
            uninsurance_rate = base_uninsurance + RNG.uniform(-0.8, 0.8) + (year - DEMO_YEARS[0]) * RNG.uniform(0.1, 0.5)
            uninsurance_rate_change = RNG.uniform(-0.5, 2.4) + (county["distance_to_topeka_miles"] / 90)
            rows.append(
                {
                    "county_fips": county["county_fips"],
                    "county_name": county["county_name"],
                    "year": year,
                    "diabetes_patients": int(max(diabetes_patients, 40)),
                    "acute_care_events": int(max(acute_care_events, 5)),
                    "diabetes_acute_care_rate": round(max(acute_care_events, 5) / max(diabetes_patients, 40) * 100, 2),
                    "uninsurance_rate": round(uninsurance_rate, 2),
                    "uninsurance_rate_change": round(uninsurance_rate_change, 2),
                    "distance_to_topeka_miles": county["distance_to_topeka_miles"],
                    "distance_to_junction_city_miles": county["distance_to_junction_city_miles"],
                }
            )
    return pd.DataFrame(rows)


def build_synthetic_campus_scores(county_panel: pd.DataFrame) -> pd.DataFrame:
    latest_panel = county_panel[county_panel["year"] == max(DEMO_YEARS)]
    rows: list[dict[str, object]] = []

    for county in COUNTY_METADATA:
        county_context = latest_panel[latest_panel["county_fips"] == county["county_fips"]].iloc[0]
        for campus in ["Topeka", "Junction City"]:
            distance = (
                county["distance_to_topeka_miles"]
                if campus == "Topeka"
                else county["distance_to_junction_city_miles"]
            )
            current_patient_volume = int(RNG.integers(20, 120))
            hospital_involvement = round(RNG.uniform(0.08, 0.34), 2)
            rows.append(
                {
                    "county_fips": county["county_fips"],
                    "county_name": county["county_name"],
                    "campus": campus,
                    "current_patient_volume": current_patient_volume,
                    "uninsurance_change": county_context["uninsurance_rate_change"],
                    "hospital_involvement": hospital_involvement,
                    "distance_to_campus_miles": distance,
                }
            )

    campus_scores = compute_campus_opportunity_score(pd.DataFrame(rows))
    return campus_scores[
        [
            "county_fips",
            "county_name",
            "campus",
            "current_patient_volume",
            "uninsurance_change",
            "hospital_involvement",
            "distance_to_campus_miles",
            "campus_opportunity_score",
        ]
    ]


def main() -> None:
    ensure_project_dirs()
    SAMPLE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    encounters = build_synthetic_encounters()
    county_panel = build_synthetic_county_panel()
    campus_scores = build_synthetic_campus_scores(county_panel)

    encounters.to_csv(SAMPLE_DATA_DIR / "synthetic_encounters.csv", index=False)
    county_panel.to_csv(SAMPLE_DATA_DIR / "synthetic_county_panel.csv", index=False)
    campus_scores.to_csv(SAMPLE_DATA_DIR / "synthetic_campus_scores.csv", index=False)

    print(f"Wrote {len(encounters)} synthetic encounters")
    print(f"Wrote {len(county_panel)} synthetic county panel rows")
    print(f"Wrote {len(campus_scores)} synthetic campus-score rows")


if __name__ == "__main__":
    main()
